# -*- coding: utf-8 -*-
"""Python Week 8 project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b32Bxwmkf-w8l8x7MD5MvgZkQLUeGd9_

##1. DATA COLLECTION
The data set being used is the Our world covid data set from kaggle

##2. DATA LOADING AND EXPLORATION
Here I import the necessary libraries to load the data and carry out the following actions on the data: check columns, preview rows identify missing values.
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/owid-covid-data.csv')

# Check columns
print("Columns in the dataset:")
print(df.columns)

# Preview the first few rows
print("\nFirst 5 rows of the dataset:")
print(df.head())

# Identify missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

"""there are some columns with missing values"""

print("\nMissing values in each column:")
print(df.isnull().sum())

"""We have now identified the columns with missing values

##3. DATA CLEANING
We will prepare the data for analysis.
"""

# Filter countries of interest
countries_of_interest = ['Kenya', 'USA', 'India']
df_filtered = df[df['location'].isin(countries_of_interest)].copy()

# Drop rows with missing dates
df_cleaned = df_filtered.dropna(subset=['date'])

# Convert date column to datetime
df_cleaned['date'] = pd.to_datetime(df_cleaned['date'])

# Handle missing numeric values using forward fill and then backward fill
numeric_cols = df_cleaned.select_dtypes(include=['number']).columns
df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(method='ffill').fillna(method='bfill')

# Verify that missing values in numeric columns are handled
print("\nMissing values in numeric columns after imputation:")
print(df_cleaned[numeric_cols].isnull().sum())

# Display the first few rows of the cleaned DataFrame
print("\nFirst 5 rows of the cleaned DataFrame:")
print(df_cleaned.head())

"""I have dealt with the missing values.
I have CONVERTED DATE column to DATE AND TIME.
I have also filtered out countries of interest.

##4. Exploratory Data Analysis
Generating descriptive statistics and exploring trends.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set a visually appealing style for the plots
sns.set_style("whitegrid")

# 1. Plot total cases over time for selected countries
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_cleaned, x='date', y='total_cases', hue='location')
plt.title('Total COVID-19 Cases Over Time')
plt.xlabel('Date')
plt.ylabel('Total Cases')
plt.legend(title='Country')
plt.tight_layout()
plt.show()

# 2. Plot total deaths over time
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_cleaned, x='date', y='total_deaths', hue='location')
plt.title('Total COVID-19 Deaths Over Time')
plt.xlabel('Date')
plt.ylabel('Total Deaths')
plt.legend(title='Country')
plt.tight_layout()
plt.show()

# 3. Compare daily new cases between countries
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_cleaned, x='date', y='new_cases', hue='location')
plt.title('Daily New COVID-19 Cases')
plt.xlabel('Date')
plt.ylabel('New Cases')
plt.legend(title='Country')
plt.tight_layout()
plt.show()

# 4. Calculate the death rate (total_deaths / total_cases)
df_cleaned['death_rate'] = df_cleaned['total_deaths'] / df_cleaned['total_cases']

# Plot the death rate over time
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_cleaned, x='date', y='death_rate', hue='location')
plt.title('COVID-19 Death Rate Over Time (Total Deaths / Total Cases)')
plt.xlabel('Date')
plt.ylabel('Death Rate')
plt.legend(title='Country')
plt.tight_layout()
plt.show()

# Display some descriptive statistics
print("\nDescriptive Statistics:")
print(df_cleaned[['total_cases', 'total_deaths', 'new_cases', 'new_deaths', 'death_rate']].describe())

# Bar chart (top countries by total cases)
# Get the latest data for each country
latest_data = df.groupby('location').tail(1)

# Sort by total cases and select the top N countries
top_n = 10  # You can change this number
top_countries_total_cases = latest_data.sort_values(by='total_cases', ascending=False).head(top_n)

plt.figure(figsize=(14, 7))
sns.barplot(x='total_cases', y='location', data=top_countries_total_cases, palette='viridis')
plt.title(f'Top {top_n} Countries by Total COVID-19 Cases (Latest Data)')
plt.xlabel('Total Cases')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

"""China is the leading country with the most cases with the country with the least cases is Croatia."""

print("Columns in the cleaned DataFrame:")
print(df_cleaned.columns)

"""##5. Visualizing Vaccination Progress"""

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_cleaned, x='date', y='total_vaccinations', hue='location')
plt.title('Cumulative COVID-19 Vaccinations Over Time')
plt.xlabel('Date')
plt.ylabel('Total Vaccinations')
plt.legend(title='Country')
plt.tight_layout()
plt.show()

"""Checking if there is population column in the cleaned dataset so that I can use it."""

if 'population' in df_cleaned.columns:
    print("Population column is available.")
else:
    print("Population column is not available in the cleaned DataFrame.")

if 'population' in df_cleaned.columns and 'people_vaccinated' in df_cleaned.columns:
    df_cleaned['percent_vaccinated'] = (df_cleaned['people_vaccinated'] / df_cleaned['population']) * 100

    # Plot the percentage of vaccinated population over time
    plt.figure(figsize=(12, 6))
    sns.lineplot(data=df_cleaned, x='date', y='percent_vaccinated', hue='location')
    plt.title('Percentage of Population Vaccinated (at least one dose) Over Time')
    plt.xlabel('Date')
    plt.ylabel('Percent Vaccinated')
    plt.legend(title='Country')
    plt.tight_layout()
    plt.show()
else:
    print("Cannot calculate percentage vaccinated. Ensure 'population' and 'people_vaccinated' columns are present.")

if 'people_fully_vaccinated_per_hundred' in df_cleaned.columns:
    # Plot the percentage of fully vaccinated population over time
    plt.figure(figsize=(12, 6))
    sns.lineplot(data=df_cleaned, x='date', y='people_fully_vaccinated_per_hundred', hue='location')
    plt.title('Percentage of Population Fully Vaccinated Over Time')
    plt.xlabel('Date')
    plt.ylabel('Percent Fully Vaccinated')
    plt.legend(title='Country')
    plt.tight_layout()
    plt.show()
else:
    print("Column 'people_fully_vaccinated_per_hundred' is not available.")

"""##6. Building a Choropleth Map
Visualizing cases by country on a world map.
"""

import sys
!{sys.executable} -m pip install plotly

#import plotly.express as px
import pandas as pd # Import pandas if not already imported in this cell

# Get the latest data for each country from the original dataframe
latest_data = df.groupby('location').tail(1)

# Extract the 'total_cases' for the latest data and store it in a series
latest_cases_series = latest_data.set_index('location')['total_cases']

# Convert the latest_cases_series back to a DataFrame
latest_cases_df = latest_cases_series.reset_index()
latest_cases_df.columns = ['location', 'total_cases']

# Create the choropleth map
fig = px.choropleth(latest_cases_df,
                    locations='location',
                    locationmode='country names',
                    color='total_cases',
                    hover_name='location',
                    color_continuous_scale=px.colors.sequential.Plasma,
                    title='Total COVID-19 Cases (Latest Available Date)')
fig.show()

"""##INSIGHTS FROM THE DATA
---

The cleaned dataset focuses on Kenya, the USA, and India, allowing a comparative analysis of how the pandemic evolved in these countries. From the line plots showing total cases over time, it’s evident that the USA experienced the most significant rise in cases, followed by India, with Kenya having far fewer cases overall. This aligns with population sizes and global COVID-19 trends, but also highlights stark differences in testing capacity, health infrastructure, and case reporting.

When examining total deaths, a similar pattern emerges—deaths in the USA far exceed those in India and Kenya. However, the death rate (total deaths divided by total cases) fluctuates over time. At certain points, Kenya shows a comparatively higher death rate despite having fewer total cases, which could suggest challenges in healthcare accessibility, delayed reporting, or under-testing that misses mild or asymptomatic cases.

The daily new cases plot reflects the wave-like nature of the pandemic. India shows sharp peaks, particularly during its second wave, while the USA exhibits more sustained, broader waves. Kenya’s curve is flatter, which again could point to limited testing or more effective early containment, though it's likely a mix of both data and infrastructure limitations.

Vaccination data reveals that the USA ramped up vaccination efforts quickly and reached high cumulative totals early on. India shows a steep growth trajectory but starts later. Kenya lags significantly in both total and percentage vaccinated figures. This discrepancy highlights global vaccine inequity, with lower-income nations like Kenya facing delays in vaccine access and rollout.

The choropleth map and bar chart of the top 10 countries by total cases visually confirm that COVID-19 burden was highly concentrated in countries with large populations and dense urban centers. Nations like the USA, India, and Brazil dominate the global case count. These visualizations emphasize the need for sustained international support and equitable resource distribution.

Overall, the findings suggest that stronger health systems and early access to vaccines correlate with better outcomes, but there are exceptions due to socioeconomic, political, and structural differences. For recommendations, governments in lower-vaccinated countries should focus on improving vaccine outreach and supply chains. Globally, preparedness and transparency in reporting need improvement for future pandemics, along with collaborative efforts to ensure equitable health interventions.

"""